# Generated by Django 5.0.1 on 2024-02-22 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityTApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=30)),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityTApp.tripplan')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityTApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityTApp.ticket')),
            ],
        ),
    ]
