# Generated by Django 5.0.1 on 2024-02-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityTApp', '0003_agent_agency_logo_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agency_logo',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='logo/'),
        ),
    ]
