# Generated by Django 5.0.1 on 2024-03-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityTApp', '0005_rename_name_agent_username_rename_name_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='gst_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='agent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
