# Generated by Django 5.0.1 on 2024-03-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityTApp', '0006_alter_agent_gst_no_alter_agent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agency_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='email_id',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
