# Generated by Django 5.0.1 on 2024-03-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityTApp', '0007_alter_agent_agency_name_alter_agent_email_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
