# Generated by Django 5.0.1 on 2024-03-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityTApp', '0008_agent_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
