# Generated by Django 5.0.1 on 2024-03-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityTApp', '0009_alter_agent_last_login_alter_tripplan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplan',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
