# Generated by Django 5.0.1 on 2024-03-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityTApp', '0010_tripplan_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplan',
            name='extra_info',
            field=models.TextField(default=None),
        ),
    ]
