# Generated by Django 5.0.1 on 2024-03-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cityTApp', '0012_alter_tripplan_trip_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripplan',
            old_name='departure_data',
            new_name='departure_date',
        ),
    ]
