# Generated by Django 5.0.1 on 2024-03-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityTApp', '0015_remove_tripplan_attraction_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='att_img',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='attraction/'),
        ),
    ]
