# Generated by Django 5.0.1 on 2024-03-05 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cityTApp', '0018_alter_attraction_trip_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attraction',
            old_name='att_img',
            new_name='att_imgs',
        ),
    ]
