# Generated by Django 5.0.1 on 2024-03-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityTApp', '0019_rename_att_img_attraction_att_imgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
