# Generated by Django 5.0.1 on 2024-03-28 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityTApp', '0021_tripplan_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempTicket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='passenger',
            name='ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityTApp.tempticket'),
        ),
    ]
