# Generated by Django 5.0.1 on 2024-03-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityTApp', '0023_rename_id_tempticket_temp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='ticket_id',
            field=models.IntegerField(),
        ),
    ]
