# Generated by Django 5.0.1 on 2024-03-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityTApp', '0024_alter_passenger_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
