# Generated by Django 5.0.1 on 2024-04-03 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityTApp', '0025_alter_passenger_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityTApp.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
