# Generated by Django 5.0.1 on 2024-04-03 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cityTApp', '0026_alter_passenger_ticket_id_alter_ticket_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='ticket_id',
            new_name='t_id',
        ),
    ]
