# Generated by Django 5.0.1 on 2024-04-03 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cityTApp', '0028_rename_t_id_passenger_ticket_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tempTicket',
        ),
    ]
